name: Cuneos Release

on:
  workflow_call:
    secrets:
      RELEASE_TOKEN:
        required: true
env:
  HUSKY: 0

jobs:
  main:
    runs-on: ubuntu-latest
    name: Run
    steps:
      - name: Checkout [Pull Request]
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.RELEASE_TOKEN }}
          fetch-depth: 0

      - name: Checkout [Default Branch]
        uses: actions/checkout@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          fetch-depth: 0

      - name: Track main
        run: git branch --track main origin/main || echo "Already done"

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: ${{ github.base_ref }}

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Install Dependencies
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
          run_install: false

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          RUN=CI pnpm build

      - name: Release
        if: ${{ success() && (github.event_name != 'pull_request' || github.event.action == 'closed' && github.event.pull_request.merged == true) }}
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NPM_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          RUN=CI pnpm release
